name: Contunious Integration and deployment

on:
  push:
    branches:
      - master
      - 
env:
  AZURE_WEBAPP_NAME: 'weatherforecast-ci-cd'
  AZURE_WEBAPP_PACKAGE_PATH: 'myapp/'
  DOTNET_VERSION: '5.0.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build and restore projcet
        run: dotnet build
        
      - name: Publish Web project to folder
        run: dotnet publish WeatherForecast_CI_CD -o myapp -c Release --no-build
      
      - name: Run tests
        run: dotnet test -c Release --no-restore
        
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUR_WEBAPP_PUBLISH_SECRET  }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}